//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int payment_id { get; set; }
        public int booking_id { get; set; }
        public string payment_status { get; set; }
        public string payment_method { get; set; }
        public System.DateTime payment_date { get; set; }
        public decimal payment_amount { get; set; }
    
        public virtual payment payments1 { get; set; }
        public virtual payment payment1 { get; set; }
    }
}
